#ifndef _ESXI_SENSE_DECODE_H
#define _ESXI_SENSE_DECODE_H

#ifdef __cplusplus    //__cplusplus是cpp中自定义的一个宏
extern "C" {          //告诉编译器，这部分代码按C语言的格式进行编译，而不是C++的
#endif

#define SENSE_NAME_LEN 256
#define SENSE_DESC_LEN 512

typedef enum sense_type {
    TYPE_HOST_STATUS, 
    TYPE_DEVICE_STATUS,
    TYPE_PLUGIN_STATUS,
    TYPE_SENSE_KEY,
    TYPE_ADDITIONAL_SENSE_DATA,
} sense_type_e;

typedef struct sense_reason {
    // sense_type_e type;
    int code;
    char name[SENSE_NAME_LEN+1];
    char desc[SENSE_DESC_LEN+1];
} sense_reason_t;


#define VMK_SCSI_HOST_OK 0x00
#define VMK_SCSI_HOST_NO_CONNECT 0x01
#define VMK_SCSI_HOST_BUS_BUSY   0x02
#define VMK_SCSI_HOST_TIMEOUT    0x03
#define VMK_SCSI_HOST_BAD_TARGET 0x04
#define VMK_SCSI_HOST_ABORT      0x05
#define VMK_SCSI_HOST_PARITY     0x06
#define VMK_SCSI_HOST_ERROR      0x07
#define VMK_SCSI_HOST_RESET      0x08
#define VMK_SCSI_HOST_BAD_INTR   0x09
#define VMK_SCSI_HOST_PASSTHROUGH 0x0a
#define VMK_SCSI_HOST_SOFT_ERROR  0x0b
#define VMK_SCSI_HOST_RETRY       0x0c
#define VMK_SCSI_HOST_REQUEUE     0x0d

#define VMK_SCSI_DEVICE_NUM 12
#define VMK_SCSI_DEVICE_GOOD 0x00
#define VMK_SCSI_DEVICE_CHECK_CONDITION 0x02
#define VMK_SCSI_DEVICE_CONDITION_MET 0x04
#define VMK_SCSI_DEVICE_BUSY 0x08
#define VMK_SCSI_DEVICE_INTERMEDIATE 0x10
#define VMK_SCSI_DEVICE_INTERMEDIATE_CONDITION_MET 0x14
#define VMK_SCSI_DEVICE_RESERVATION_CONFLICT 0x18
#define VMK_SCSI_DEVICE_COMMAND_TERMINATED 0x22
#define VMK_SCSI_DEVICE_QUEUE_FULL 0x28
#define VMK_SCSI_DEVICE_ACA_ACTIVE 0x30
#define VMK_SCSI_DEVICE_TASK_ABORTED 0x40
#define VMK_SCSI_DEVICE_UNKNOWN      0xffff

#define VMK_SCSI_PLUGIN_NUM 10
#define VMK_SCSI_PLUGIN_GOOD 0x00
#define VMK_SCSI_PLUGIN_TRANSIENT 0x01
#define VMK_SCSI_PLUGIN_SNAPSHOT 0x02
#define VMK_SCSI_PLUGIN_RESERVATION_LOST 0x03
#define VMK_SCSI_PLUGIN_REQUEUE 0x04
#define VMK_SCSI_PLUGIN_ATS_MISCOMPARE 0x05
#define VMK_SCSI_PLUGIN_THINPROV_BUSY_GROWING 0x06
#define VMK_SCSI_PLUGIN_THINPROV_ATQUOTA 0x07
#define VMK_SCSI_PLUGIN_THINPROV_NOSPACE 0x08
#define VMK_SCSI_PLUGIN_UNKOWN 0xffff

#define VMK_SCSI_SENSE_NUM 16
#define VMK_SCSI_SENSE_NO_SENSE 0x00
#define VMK_SCSI_SENSE_RECOVERED_ERROR 0x01
#define VMK_SCSI_SENSE_NOT_READY 0x02
#define VMK_SCSI_SENSE_MEDIUM_ERROR 0x03
#define VMK_SCSI_SENSE_HARDWARE_ERROR 0x04
#define VMK_SCSI_SENSE_ILLEGAL_REQUEST 0x05
#define VMK_SCSI_SENSE_UNIT_ATTENTION 0x06
#define VMK_SCSI_SENSE_DATA_PROTECT 0x07
#define VMK_SCSI_SENSE_BLANK_CHECK 0x08
#define VMK_SCSI_SENSE_VENDOR_SPECIFIC 0x09
#define VMK_SCSI_SENSE_COPY_ABORTED 0x0A
#define VMK_SCSI_SENSE_ABORTED_COMMAND 0x0B
#define VMK_SCSI_SENSE_VOLUME_OVERFLOW 0x0D
#define VMK_SCSI_SENSE_MISCOMPARE 0x0E
#define VMK_SCSI_SENSE_COMPLETED 0x0F
#define VMK_SCSI_SENSE_UNKNOWN 0xFFFF

#ifdef __cplusplus
}
#endif

#endif